stages:
  - build
  - deploy

variables:
  DEV_DEPLOY_DIR: '/var/host/www/$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME/www-$CI_COMMIT_REF_NAME'

.build:
  stage: build
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - public/
  only:
    - master
  script:
    - yarn install --production
    - env > .env
    #    - export APP_SENTRY_DSN="REPLACE_WITH_REAL_SENTRY_DSN"
    - node webpack production
    - echo "$CI_COMMIT_REF_NAME-$CI_JOB_ID" > $CI_PROJECT_DIR/public/version.txt

build_dev:
  extends: .build
  only:
    - master
  variables:
    APP_ENV: preview
    APP_BACKEND_URL: https://boilerplateadmin12345.kozhin.dev

deploy:
  stage: deploy
  only:
    - master
    - stage
  tags:
    - dev-server
  variables:
    GIT_STRATEGY: none
  script:
    - echo "$CI_PROJECT_DIR"
    - echo "$DEV_DEPLOY_DIR"
    - mkdir -p $DEV_DEPLOY_DIR
    - rsync
      --recursive
      --delete
      --verbose
      --human-readable
      $CI_PROJECT_DIR/ $DEV_DEPLOY_DIR
